import Image from "next/image";
import CtaLink from "@/components/public/CtaLink";
import ProcessExplorer from "./ProcessExplorer";
import HeroArtifact from "./HeroArtifact";
import "./refresh.css";

// An explicit origin keeps the isolated preview connected to current, published routes.
// On integration into the current production branch, pass origin="".
export default function RefreshHome({ origin = "https://veretennikov.info" }: { origin?: string }) {
  const url = (path: string) => `${origin}${path}`;
  return <div className="sr-site">
      <section className="sr-hero sr-wrap" aria-labelledby="hero-title">
        <div className="sr-masthead"><span>ИИ · Цифровые продукты · Визуальные коммуникации</span><span>Екатеринбург / работаем по России</span></div>
        <div className="sr-hero-grid"><div className="sr-hero-copy"><p className="sr-label sr-blue">Студия сложных решений</p><h1 id="hero-title">Сложное<br/><em>становится реальным.</em></h1><p className="sr-lead">Соединяем стратегию, ИИ, разработку и визуальный язык. Собираем решение целиком — от первой гипотезы до результата, которым можно пользоваться.</p><div className="sr-actions"><CtaLink className="sr-button" href={url("/razbor")} goalName="razbor_cta" goalParams={{ place: "homepage_refresh" }}>Обсудить задачу <span aria-hidden="true">↗</span></CtaLink><a className="sr-text-link" href="#work">Смотреть проекты <span aria-hidden="true">↓</span></a></div><p className="sr-note">Первый разговор — 40 минут · без презентаций и продажи в лоб</p></div>
        <HeroArtifact /></div>
      </section>
      <div className="sr-trust"><div className="sr-wrap sr-trust-inner"><p><strong>12 лет</strong><span>проектов для промышленности<br/>и корпоративных заказчиков</span></p><div><span className="sr-label">Среди заказчиков студии · разные типы проектов</span><ul><li>Белоярская АЭС</li><li>Ростелеком</li><li>УБРиР</li><li>Технэкс</li></ul></div></div></div>
      <section id="work" className="sr-section sr-wrap" aria-labelledby="work-title"><div className="sr-section-heading"><div><p className="sr-label">01 / Опыт в действии</p><h2 id="work-title">От задачи — к тому,<br/>что можно показать.</h2></div><a className="sr-text-link" href={url("/cases")}>Все проекты <span aria-hidden="true">↗</span></a></div>
        <div className="sr-project-grid">
          <a className="sr-project" href={url("/show/industrial-cooperation")}><div className="sr-project-visual sr-cooperation"><span className="sr-visual-caption">Схема решения / AI + разработка</span><div className="sr-coop-map" aria-hidden="true"><span>Запрос</span><i/><b>Подбор<br/>партнёров</b><i/><span>Оператор</span></div><div className="sr-visual-bottom"><span>Промышленная кооперация</span><span>↗</span></div></div><p className="sr-label">Региональный союз промышленников</p><h3>Найти партнёра<br/>по производственной задаче.</h3><p>AI-помощник превращает свободный запрос в подбор исполнителей под контролем оператора.</p><span className="sr-project-link">Разобрать проект <span aria-hidden="true">↗</span></span></a>
          <a className="sr-project" href={url("/show/road-analytics-platform")}><div className="sr-project-visual sr-road"><span className="sr-visual-caption">Схема решения / цифровая платформа</span><svg viewBox="0 0 340 160" aria-hidden="true" fill="none"><path d="M-10 125 105 80 175 105 355 20M-10 45 100 65 170 35 240 90 350 110" stroke="currentColor" strokeWidth="2"/><path d="m85 0 20 80-30 80m150-170 15 100 35 70" stroke="currentColor" strokeOpacity=".35"/><circle cx="105" cy="80" r="9" fill="var(--cobalt)"/><circle cx="240" cy="90" r="6" fill="var(--cobalt)"/><path d="M113 73 142 45h63" stroke="var(--cobalt)"/><rect x="141" y="17" width="93" height="28" fill="var(--paper)"/><text x="150" y="36" fill="var(--ink)" fontSize="11">Инцидент →</text></svg><div className="sr-visual-bottom"><span>Данные → решение → действие</span><span>↗</span></div></div><p className="sr-label">Дорожно-транспортная отрасль</p><h3>Видеть обстановку.<br/>Управлять инцидентами.</h3><p>Платформа объединяет аналитику аварийности и оперативное управление дорожными инцидентами.</p><span className="sr-project-link">Разобрать проект <span aria-hidden="true">↗</span></span></a>
          <a className="sr-project" href={url("/show/belojarskaya-aes")}><div className="sr-project-visual sr-film"><Image src="https://kinescopecdn.net/c0199d68-af23-48c2-8604-76530c1ffb01/posters/652f809f-cb12-490e-bb5c-52c5ff51cfa3/md/d9f58162-a58c-40ad-8681-d24b90556b35.jpg" alt="Кадр из корпоративного фильма Белоярской АЭС" fill sizes="(max-width: 700px) 100vw, (max-width: 1000px) 50vw, 380px"/><span className="sr-visual-caption">Реальный проект / промышленное видео</span><div className="sr-visual-bottom"><span>Фильм · 11:57</span><span>↗</span></div></div><p className="sr-label">Белоярская АЭС</p><h3>Показать технологию.<br/>Рассказать о людях.</h3><p>Съёмка в технологических зонах, архив и VFX — в корпоративном фильме к юбилею станции.</p><span className="sr-project-link">Смотреть проект <span aria-hidden="true">↗</span></span></a>
        </div>
      </section>
      <section id="solutions" className="sr-solutions sr-section"><div className="sr-wrap"><div className="sr-section-heading"><div><p className="sr-label">02 / Найдите свой процесс</p><h2>Меньше ручной работы.<br/>Больше управляемости.</h2></div><p className="sr-heading-note">Выберите ситуацию.<br/>Посмотрите, что меняется.</p></div><ProcessExplorer origin={origin}/><div className="sr-other"><span>Пока не знаете, с чего начать?</span><a className="sr-text-link" href={url("/diagnostika")}>Диагностика процессов <span aria-hidden="true">↗</span></a><a className="sr-text-link" href={url("/programs")}>Программы по ИИ для руководителей <span aria-hidden="true">↗</span></a></div></div></section>
      <section className="sr-section sr-wrap" aria-labelledby="method-title"><div className="sr-section-heading"><div><p className="sr-label">03 / Управляемый путь</p><h2 id="method-title">Сначала считаем.<br/>Потом строим.</h2></div><p className="sr-heading-note">У каждого этапа — результат.<br/>И решение, стоит ли идти дальше.</p></div><div className="sr-method">{[
        ["00", "Разбор", "40 минут", "Понять задачу", "Берём одну рабочую операцию. После разговора — короткое письменное резюме и рекомендуемый следующий шаг."],
        ["01", "Диагностика", "1–2 недели", "Оценить эффект", "Карта процесса, исходные показатели, гипотезы и план. Отчёт можно реализовать самостоятельно или с другим подрядчиком."],
        ["02", "Пилот", "4–8 недель", "Проверить на данных", "Работающий прототип и метрики качества. Решаем: внедрять, доработать или остановиться."],
        ["03", "Внедрение", "2–4 месяца", "Встроить в работу", "Интеграции, права доступа, документация и обучение команды. Далее — развитие и поддержка по отдельной договорённости."],
      ].map(([n,title,time,result,detail])=><details key={n}><summary><span className="sr-method-number">{n}</span><h3>{title}</h3><span className="sr-method-result">{result}</span><span className="sr-method-time">{time}</span><span className="sr-disclosure" aria-hidden="true">+</span></summary><p>{detail}</p></details>)}</div><p className="sr-method-note">Если ИИ не нужен — предложим обычную автоматизацию или изменение процесса.</p></section>
      <section className="sr-heritage"><div className="sr-wrap sr-heritage-grid"><div><p className="sr-label">04 / То, что отличает студию</p><h2>Понимать сложное.<br/><em>Делать его понятным.</em></h2></div><div><p>Двенадцать лет мы работаем с промышленными технологиями: снимаем в цехах, создаём 3D и объясняем процессы, которые невозможно увидеть камерой.</p><p>Сегодня этот опыт помогает погружаться в задачи цифровых систем. Видео, 3D и интерактив остаются самостоятельным направлением.</p><a className="sr-text-link" href={url("/production")}>Промышленное видео, 3D и интерактив <span aria-hidden="true">↗</span></a></div></div></section>
      <section className="sr-section sr-wrap sr-faq" aria-labelledby="faq-title"><div><p className="sr-label">05 / До начала работы</p><h2 id="faq-title">Важные вопросы.</h2></div><div>{[
        ["Данные останутся внутри компании?", "Архитектуру размещения и права доступа обсуждаем до начала работ. Для чувствительных данных рассматриваем локальные модели и размещение в вашем контуре."],
        ["Что будет с системой после сдачи?", "Передаём документацию и доступы, обучаем команду. Развитие и поддержку согласуем отдельно — систему можно вести самостоятельно."],
        ["Сколько стоит начать?", "Первый разбор — бесплатно, 40 минут. После него можно определить объём диагностики. Стоимость разработки зависит от данных, интеграций и задачи."],
      ].map(([q,a])=><details key={q}><summary>{q}<span className="sr-disclosure" aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
      <section className="sr-contact"><div className="sr-wrap sr-contact-grid"><div><p className="sr-label">Начнём с конкретной задачи</p><h2>Один процесс.<br/><em>Сорок минут.</em></h2><p>Посмотрим, где уходит время и что имеет смысл автоматизировать. На выходе — письменное резюме и следующий шаг.</p></div><div><CtaLink className="sr-button" href={url("/razbor")} goalName="razbor_cta" goalParams={{ place: "homepage_refresh" }}>Разобрать мой процесс <span aria-hidden="true">↗</span></CtaLink><p className="sr-note">Бесплатно · ответ в течение рабочего дня</p><a className="sr-text-link" href={url("/brief")}>Уже есть задача? Перейти к брифу <span aria-hidden="true">↗</span></a></div></div></section>

  </div>;
}
